[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.uvicorn"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn parser-server:app --host 0.0.0.0 --port $PORT"

